name: Deploy to Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@0.0.4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist
        BUILD_SCRIPT: |
          npm install && npm run-script build
          echo 'docs.viz.cx' > docs/.vuepress/dist/CNAME
